name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/workspace:latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ env.DOCKER_IMAGE }}

  push_image:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Docker login
      uses: docker/login-action@v3.2.0
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: docker push ${{ env.DOCKER_IMAGE }}
        
    
